name: Sync Google Doc to Markdown

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch: # allows manual run

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Fetch Google Doc and Convert to MD
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          DOC_ID: ${{ secrets.DOC_ID }}
        run: |
          echo "$GOOGLE_CREDENTIALS" > credentials.json
          python scripts/google_doc_to_md.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Updated Markdown from Google Doc" || echo "No changes to commit"
          git push
